---
- name: docker (jessie) - add backports repo
  apt_repository: repo='deb http://http.debian.net/debian jessie-backports main non-free contrib' update_cache=yes state=present

- name: docker (jessie) - install docker
  apt: pkg=docker.io
  notify: docker - start and enable

- name: docker - add cgroup options to kernel boot arguments
  lineinfile: dest=/etc/default/grub line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' state=present
  register: grub

- name: docker - update grub and reboot
  shell: shutdown -r now
  when: grub|changed
  register: reboot

- name: docker - wait for reboot
  local_action: wait_for host={{ inventory_hostname }}
    state=started
    delay=30
    timeout=600
  sudo: no
  when: grub|changed
