---
- include: kernel.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'

- include: docker.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'

- include: docker_jessie.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'
