- name: add apache group
  group: name=apache state=present

- name: add apache user
  user: name=apache group=apache

- name: install apache2-mpm-event
  action: apt pkg=apache2-mpm-event default_release=wheezy-backports state=latest

- name: chown /var/lock/apache2
  action: file path=/var/lock/apache2 owner=apache group=apache state=directory

- name: create ports.conf
  action: template src=ports.conf dest=/etc/apache2/ports.conf
  notify:
    - restart apache

- name: create envvars
  action: template src=envvars dest=/etc/apache2/envvars
  notify:
    - restart apache