- name: Set MariaDB root password
  command: "debconf-set-selections <<< 'mysql-server-10.0 mysql-server/root_password password {{mysql_root_password}}'"
  command: "debconf-set-selections <<< 'mysql-server-10.0 mysql-server/root_password_again password {{mysql_root_password}}'"
  changed_when: False # Never report as changed

- name: Add MariaDB apt key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xcbcb082a1bb943db

- name: Add MariaDB apt repository
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian wheezy main'
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'

- name: (jessie) Add MariaDB apt repository
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian jessie main'
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

- name: Install MariaDB
  apt: pkg=mariadb-server

- name: install mysqldb for ansible
  action: apt pkg=python-mysqldb state=installed

- name: install mysql dev files
  action: apt pkg=libmariadbclient-dev state=installed
