---

- hosts: all
  sudo: True

  roles:
    - { role: docker, tags: ["docker"] }
    - { role: mariadb, tags: ["mariadb", "mysql"] }
    - { role: postgres, tags: ["postgres"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: apache, tags: ["apache"] }
    - { role: go1.4, tags: ["go1.4"] }
    - { role: manager, tags: ["manager"] }