---
- name: copy systemd cron config
  action: template src=systemd_cron.service dest=/etc/systemd/system/manager-cron.service
  notify:
    - reload systemd
    - restart cron

- name: copy systemd manager config
  action: template src=systemd_manager.service dest=/etc/systemd/system/manager-manager.service
  notify:
    - reload systemd
    - restart manager

- name: copy systemd proxy config
  action: template src=systemd_proxy.service dest=/etc/systemd/system/manager-proxy.service
  notify:
    - reload systemd
    - restart proxy

- name: copy systemd ssh config
  action: template src=systemd_ssh.service dest=/etc/systemd/system/manager-ssh.service
  notify:
    - reload systemd
    - restart ssh

- name: flush handlers
  meta: flush_handlers

- name: start & enable cron service
  action: service state=started enabled=yes name=manager-cron

- name: start & enable manager service
  action: service state=started enabled=yes name=manager-manager

- name: start & enable proxy service
  action: service state=started enabled=yes name=manager-proxy

- name: start & enable ssh service
  action: service state=started enabled=yes name=manager-ssh
