---

- name: add manager group
  group: name=manager state=present

- name: add manager user
  user: name=manager group=manager


- name: add manager user to docker
  user: name=manager append=true groups=docker

- name: add manager user to sudo
  user: name=manager append=true groups=sudo

- name: add manager user to nginx
  user: name=manager append=true groups=nginx

- name: add manager user to apache
  user: name=manager append=true groups=apache

- name: install build essential
  action: apt pkg={{item}} state=installed
  with_items:
    - build-essential
    - gcc
    - python-dev
    - python-virtualenv

- name: copy init.d config
  action: template src=init_d_manager.conf dest=/etc/init.d/manager mode=700

- name: set manager to run on boot
  shell: update-rc.d manager defaults

- name: copy init.d config
  action: template src=init_d_proxy.conf dest=/etc/init.d/manager-proxy mode=700

- name: set manager to run on boot
  shell: update-rc.d manager-proxy defaults

- name: create log folder
  file: path=/var/log/manager/ state=directory

- name: create manager-shell log file
  file: path=/var/log/manager/manager-shell.log state=touch
