---

- name: add manager group
  group: name=manager state=present

- name: add manager user
  user: name=manager group=manager


- name: add manager user to docker
  user: name=manager append=true groups=docker

- name: add manager user to sudo
  user: name=manager append=true groups=sudo

- name: add manager user to nginx
  user: name=manager append=true groups=nginx

- name: install build essential
  action: apt pkg={{item}} state=installed
  with_items:
    - build-essential
    - gcc
    - python-dev
